Repository eclipse-edc/IdentityHub, pull requests merged in 2022-11, with the labels that each got.

#55 chore(groupId): rename project groupId to org.eclipse.edc
  client-cli/README.md
  core/identity-hub/bin/main/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  gradle.properties
Labels: refactoring

#57 chore: removes last @EdcSetting
  extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/IdentityHubApiExtension.java
Labels: refactoring

#60 chore: use standard version property
  build.gradle.kts
Labels: refactoring

#61 build: add workflow to explicitly trigger Jenkins
  .github/workflows/trigger_snapshot.yml
Labels: enhancement

#62 chore: use SNAPSHOT version of EDC
  .github/workflows/verify.yaml
  settings.gradle.kts
Labels: build
