Repository eclipse-edc/IdentityHub, pull requests merged in 2022-12, with the labels that each got.

#65 feat(build): add workflow_dispatch event trigger
  .github/workflows/verify.yaml
Labels: build

#66 feat(workflows): add discord webhook for issues, discussions and pull requests
  .github/workflows/close-inactive-issues.yml
  .github/workflows/discord-webhook.yml
  .github/workflows/first-interaction.yml
  .github/workflows/scan-pull-request.yaml
Labels: no-changelog

#67 chore: updated code to accomodate for latest nimbus
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/CollectionsWriteProcessor.java
Labels: build, dependencies

#71 build: upgrade Gradle version to 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#69 feat(build): add strict checkstyle on file header #61
  extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/IdentityHubApiConfiguration.java
  resources/checkstyle-config.xml
Labels: enhancement, build

#74 refactor: protocol clean up and extension for dataFormat
  core/identity-hub-client/src/main/java/org/eclipse/edc/identityhub/client/IdentityHubClientImpl.java
  core/identity-hub-client/src/test/java/org/eclipse/edc/identityhub/client/IdentityHubClientImplTest.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/IdentityHubExtension.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/CollectionsQueryProcessor.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/CollectionsWriteProcessor.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/FeatureDetectionReadProcessor.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/InterfaceNotImplementedProcessor.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/data/DataValidatorRegistryImpl.java
  core/identity-hub/src/main/java/org/eclipse/edc/identityhub/processor/data/JwtVerifiableCredentialValidator.java
  core/identity-hub/src/test/java/org/eclipse/edc/identityhub/processor/CollectionsWriteProcessorTest.java
  extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/controller/IdentityHubController.java
  extensions/identity-hub-api/src/test/java/org/eclipse/edc/identityhub/api/IdentityHubApiTest.java
  extensions/store/sql/identity-hub-store-sql/docs/schema.sql
  extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStore.java
  extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/schema/BaseSqlIdentityHubStatements.java
  extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/schema/IdentityHubStatements.java
  resources/openapi/yaml/identity-hub-api.yaml
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/Descriptor.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/MessageResponseObject.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/Record.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/RequestObject.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/ResponseObject.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/model/Status.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/processor/data/DataValidator.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/processor/data/DataValidatorRegistry.java
  spi/identity-hub-spi/src/test/java/org/eclipse/edc/identityhub/spi/credentials/model/RecordTest.java
  spi/identity-hub-store-spi/src/main/java/org/eclipse/edc/identityhub/store/spi/IdentityHubRecord.java
  spi/identity-hub-store-spi/src/testFixtures/java/org/eclipse/edc/identityhub/store/spi/IdentityHubStoreTestBase.java
Labels: enhancement

#79 build(deps): remove unnecessary bouncycastle dependencies
  .github/workflows/verify.yaml
  client-cli/build.gradle.kts
  system-tests/build.gradle.kts
Labels: dependencies
