Repository eclipse-edc/IdentityHub, pull requests merged in 2023-01, with the labels that each got.

#80 refactor(SqlIdentityHubStore): apply AbstractSqlStore class and PostgresqlStoreSetupExtension in test
  extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStore.java
  extensions/store/sql/identity-hub-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/SqlIdentityHubStoreExtension.java
  extensions/store/sql/identity-hub-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/PostgresParticipantStoreTest.java
Labels: refactoring

#82 chore(build): fix verifier-jwt artifact name
  extensions/identity-hub-verifier-jwt/build.gradle.kts
Labels: build

#81 feat(IdentityHubStore): provide CosmosDB implementation of `IdentityHubStore`
  .github/workflows/verify.yaml
  extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStore.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreConfig.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreExtension.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocument.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreIntegrationTest.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocumentSerializationTest.java
  extensions/store/sql/identity-hub-store-sql/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#84 refactor: format settings.gradle.kts
  settings.gradle.kts
Labels: refactoring

#86 refactor: Use `EdcHttpClient`
  client-cli/build.gradle.kts
  client-cli/src/main/java/org/eclipse/edc/identityhub/cli/AddVerifiableCredentialCommand.java
  client-cli/src/main/java/org/eclipse/edc/identityhub/cli/CryptoUtils.java
  client-cli/src/main/java/org/eclipse/edc/identityhub/cli/GetSelfDescriptionCommand.java
  client-cli/src/main/java/org/eclipse/edc/identityhub/cli/IdentityHubCli.java
  client-cli/src/main/java/org/eclipse/edc/identityhub/cli/SelfDescriptionCommand.java
  client-cli/src/test/java/org/eclipse/edc/identityhub/cli/CliTestUtils.java
  client-cli/src/test/java/org/eclipse/edc/identityhub/cli/VerifiableCredentialsCommandTest.java
  core/identity-hub-client/build.gradle.kts
  core/identity-hub-client/src/main/java/org/eclipse/edc/identityhub/client/IdentityHubClientImpl.java
  core/identity-hub-client/src/test/java/org/eclipse/edc/identityhub/client/IdentityHubClientImplIntegrationTest.java
  core/identity-hub-client/src/test/java/org/eclipse/edc/identityhub/client/IdentityHubClientImplTest.java
  core/identity-hub-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/CredentialsVerifierExtension.java
  core/identity-hub-verifier/src/test/java/org/eclipse/edc/identityhub/verifier/IdentityHubCredentialsVerifierTest.java
  extensions/credentials/identity-hub-credentials-jwt/src/main/java/org/eclipse/edc/identityhub/credentials/jwt/JwtCredentialFactory.java
  extensions/credentials/identity-hub-credentials-jwt/src/test/java/org/eclipse/edc/identityhub/credentials/jwt/JwtCredentialFactoryTest.java
  extensions/identity-hub-api/build.gradle.kts
  extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/IdentityHubApiExtension.java
  extensions/identity-hub-api/src/main/java/org/eclipse/edc/identityhub/api/controller/IdentityHubController.java
  extensions/identity-hub-api/src/test/java/org/eclipse/edc/identityhub/api/IdentityHubApiTest.java
  extensions/identity-hub-verifier-jwt/src/test/java/org/eclipse/edc/identityhub/verifier/jwt/CredentialsVerifierExtensionTest.java
  extensions/identity-hub-verifier-jwt/src/test/java/org/eclipse/edc/identityhub/verifier/jwt/IdentityHubJwtCredentialsVerifierTest.java
  extensions/self-description-api/build.gradle.kts
  extensions/self-description-api/src/main/java/org/eclipse/edc/identityhub/api/selfdescription/SelfDescriptionApiExtension.java
  extensions/self-description-api/src/main/java/org/eclipse/edc/identityhub/api/selfdescription/controller/SelfDescriptionApi.java
  extensions/self-description-api/src/main/java/org/eclipse/edc/identityhub/api/selfdescription/controller/SelfDescriptionController.java
  extensions/self-description-api/src/main/java/org/eclipse/edc/identityhub/api/selfdescription/loader/SelfDescriptionLoader.java
  extensions/self-description-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/self-description-api/src/main/resources/default-self-description.json
  extensions/self-description-api/src/test/java/org/eclipse/edc/identityhub/api/selfdescription/controller/SelfDescriptionApiTest.java
  extensions/self-description-api/src/test/java/org/eclipse/edc/identityhub/api/selfdescription/controller/SelfDescriptionApiWithConfigTest.java
  extensions/self-description-api/src/test/java/org/eclipse/edc/identityhub/api/selfdescription/controller/SelfDescriptionDefaultApiTest.java
  extensions/self-description-api/src/test/java/org/eclipse/edc/identityhub/api/selfdescription/loader/SelfDescriptionLoaderTest.java
  extensions/self-description-api/src/test/resources/invalid-self-description.txt
  extensions/self-description-api/src/test/resources/self-description.json
  launcher/build.gradle.kts
  resources/openapi/yaml/identity-hub.yaml
  resources/openapi/yaml/self-description-api.yaml
  settings.gradle.kts
  spi/identity-hub-client-spi/src/main/java/org/eclipse/edc/identityhub/client/spi/IdentityHubClient.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/credentials/model/VerifiableCredential.java
  spi/identity-hub-spi/src/testFixtures/java/org/eclipse/edc/identityhub/junit/testfixtures/VerifiableCredentialTestUtil.java
  system-tests/src/test/java/org/eclipse/edc/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java
Labels: enhancement

#85 chore: remove publications
  core/identity-hub-client/build.gradle.kts
  core/identity-hub-credentials-verifier/build.gradle.kts
  core/identity-hub-credentials-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/AggregatedResult.java
  core/identity-hub-credentials-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/CredentialsVerifierExtension.java
  core/identity-hub-credentials-verifier/src/main/java/org/eclipse/edc/identityhub/verifier/IdentityHubCredentialsVerifier.java
  core/identity-hub-credentials-verifier/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/identity-hub-credentials-verifier/src/test/java/org/eclipse/edc/identityhub/verifier/IdentityHubCredentialsVerifierTest.java
  core/identity-hub/build.gradle.kts
  extensions/credentials/identity-hub-credentials-jwt/build.gradle.kts
  extensions/identity-hub-api/build.gradle.kts
  extensions/identity-hub-verifier-jwt/build.gradle.kts
  extensions/self-description-api/build.gradle.kts
  extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
  extensions/store/sql/identity-hub-store-sql/build.gradle.kts
  identity-hub-cli/README.md
  identity-hub-cli/build.gradle.kts
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/AddVerifiableCredentialCommand.java
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/CliException.java
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/CryptoUtils.java
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/IdentityHubCli.java
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/ListVerifiableCredentialsCommand.java
  identity-hub-cli/src/main/java/org/eclipse/edc/identityhub/cli/VerifiableCredentialsCommand.java
  identity-hub-cli/src/test/java/org/eclipse/edc/identityhub/cli/CliTestUtils.java
  identity-hub-cli/src/test/java/org/eclipse/edc/identityhub/cli/VerifiableCredentialsCommandTest.java
  identity-hub-cli/src/test/resources/test-private-key.pem
  identity-hub-cli/src/test/resources/test-public-key.pem
  launcher/build.gradle.kts
  settings.gradle.kts
  spi/identity-hub-client-spi/build.gradle.kts
  spi/identity-hub-spi/build.gradle.kts
  spi/identity-hub-store-spi/build.gradle.kts
  system-tests/build.gradle.kts
Labels: enhancement, no-changelog
