Repository eclipse-edc/IdentityHub, pull requests merged in 2023-06, with the labels that each got.

#105 refactor: move Azure code to Technology-Azure
  .github/workflows/verify.yaml
  extensions/store/cosmos/identity-hub-store-cosmos/build.gradle.kts
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStore.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreConfig.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreExtension.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocument.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/CosmosIdentityHubStoreIntegrationTest.java
  extensions/store/cosmos/identity-hub-store-cosmos/src/test/java/org/eclipse/edc/identityhub/store/cosmos/model/IdentityHubRecordDocumentSerializationTest.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: refactoring

#106 fix: fixed integration test, avoided overkill docker compose component
  .github/workflows/verify.yaml
  gradle/libs.versions.toml
  system-tests/README.md
  system-tests/build.gradle.kts
  system-tests/docker-compose.yml
  system-tests/src/test/java/org/eclipse/edc/identityhub/systemtests/VerifiableCredentialsIntegrationTest.java
  system-tests/src/test/resources/webdid/authority/did.json
  system-tests/src/test/resources/webdid/participant/did.json
Labels: bug, build

#110 fix: metaModelVersion -Snapshot to 0.1.3-SNAPSHOT
  gradle.properties
Labels: enhancement
