Repository eclipse-edc/IdentityHub, pull requests merged in 2024-08, with the labels that each got.

#410 feat(db): add SQL Schema Bootstrapper
  DEPENDENCIES
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/PostgresSqlService.java
  extensions/store/sql/identity-hub-credentials-store-sql/build.gradle.kts
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStoreExtension.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/resources/credentials-schema.sql
  extensions/store/sql/identity-hub-credentials-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialsStoreTest.java
  extensions/store/sql/identity-hub-did-store-sql/build.gradle.kts
  extensions/store/sql/identity-hub-did-store-sql/src/main/java/org/eclipse/edc/identityhub/did/store/sql/SqlDidResourceStoreExtension.java
  extensions/store/sql/identity-hub-did-store-sql/src/main/resources/did-schema.sql
  extensions/store/sql/identity-hub-did-store-sql/src/test/java/org/eclipse/edc/identityhub/did/store/sql/SqlDidResourceStoreTest.java
  extensions/store/sql/identity-hub-keypair-store-sql/build.gradle.kts
  extensions/store/sql/identity-hub-keypair-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStoreExtension.java
  extensions/store/sql/identity-hub-keypair-store-sql/src/main/resources/keypairs-schema.sql
  extensions/store/sql/identity-hub-keypair-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/keypair/SqlKeyPairResourceStoreTest.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/build.gradle.kts
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStoreExtension.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/resources/participant-schema.sql
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlParticipantContextStoreTest.java
  gradle/libs.versions.toml
Labels: enhancement

#419 fix: use the new JwsSignerProvider interface
  DEPENDENCIES
  core/identity-hub-core/build.gradle.kts
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-did/build.gradle.kts
  core/identity-hub-keypairs/build.gradle.kts
  core/identity-hub-participants/build.gradle.kts
  core/lib/verifiable-presentation-lib/build.gradle.kts
  core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGenerator.java
  core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablepresentation/generators/JwtPresentationGeneratorTest.java
  gradle/libs.versions.toml
  spi/verifiable-credential-spi/build.gradle.kts
Labels: bug

#418 chore: put warning in readme
  README.md
Labels: documentation

#428 fix: use RevocationServiceRegistry (new EDC feature)
  DEPENDENCIES
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/lib/credential-query-lib/src/main/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImpl.java
  core/lib/credential-query-lib/src/test/java/org/eclipse/edc/identityhub/query/CredentialQueryResolverImplTest.java
  core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablecredential/CredentialStatusCheckServiceImpl.java
  core/lib/verifiable-presentation-lib/src/test/java/org/eclipse/edc/identithub/verifiablecredential/CredentialStatusCheckServiceImplTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
Labels: bug

#430 chore: add API Version info to IdentityHub
  DEPENDENCIES
  core/presentation-api/build.gradle.kts
  core/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
  core/presentation-api/src/main/resources/presentation-api-version.json
  extensions/api/identity-api/api-configuration/src/main/java/org/eclipse/edc/identityhub/api/configuration/IdentityApiConfigurationExtension.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  gradle/libs.versions.toml
  launcher/build.gradle.kts
  resources/openapi/identity-api.version
  resources/openapi/presentation-api.version
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/IdentityHubApiContext.java
Labels: documentation, enhancement, api

#432 chore: deprecate resolution api context
  .github/workflows/verify.yaml
  README.md
  core/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/PresentationApiExtension.java
  core/presentation-api/src/main/java/org/eclipse/edc/identityhub/api/v1/PresentationApi.java
  core/presentation-api/src/main/resources/presentation-api-version.json
  docs/developer/architecture/identity-trust-protocol/identity-hub-modules.md
  docs/developer/architecture/identityhub-apis.md
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/IdentityHubApiContext.java
Labels: enhancement, api

#429 feat: check if DID exists before creating a participant
  core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextExtension.java
  core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
  core/identity-hub-participants/src/test/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImplTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
Labels: enhancement

#438 docs: adds decision record for VC create/update API
  docs/developer/decision-records/2024-08-23-identity_hub_identity_write_credentials_api/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#434 feat: Credential create/update API
  DEPENDENCIES
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  e2e-tests/api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApi.java
  extensions/api/identity-api/validators/build.gradle.kts
  extensions/api/identity-api/validators/src/main/java/org/eclipse/edc/identityhub/api/v1/validation/VerifiableCredentialManifestValidator.java
  extensions/api/identity-api/validators/src/test/java/org/eclipse/edc/identityhub/api/v1/validation/VerifiableCredentialManifestValidatorTest.java
  extensions/api/identity-api/verifiable-credentials-api/build.gradle.kts
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/VerifiableCredentialApiExtension.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/transformer/VerifiableCredentialManifestToVerifiableCredentialResourceTransformer.java
  extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
  extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/transformer/VerifiableCredentialManifestToVerifiableCredentialResourceTransformerTest.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/IdentityResource.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialManifest.java
  spi/verifiable-credential-spi/src/test/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialManifestTest.java
Labels: api

#439 build(deps): bump gradle wrapper to 8.10
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build, dependencies
