Repository eclipse-edc/IdentityHub, pull requests merged in 2025-02, with the labels that each got.

#542 docs: Add issuance process architecture document
  docs/developer/architecture/issuer/issuance/issuance.process.md
Labels: documentation

#540 docs: update architecture doc re/ VC resource
  docs/developer/architecture/identity-trust-protocol/identity.hub.architecture.md
Labels: documentation

#554 chore: re-use existing DataModelVersion
  docs/developer/architecture/issuer/issuance/issuance.process.md
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  extensions/issuance/issuance-credentials/src/test/java/org/eclipse/edc/identityhub/issuance/credentials/attestation/AttestationPipelineImplTest.java
  spi/issuance-credentials-spi/build.gradle.kts
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/model/CredentialDefinition.java
Labels: enhancement

#555 feat: implements credential definition vertical
  core/issuerservice/issuerservice-core/build.gradle.kts
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/DefaultServiceExtension.java
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryAttestationDefinitionStore.java
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryCredentialDefinitionStore.java
  core/issuerservice/issuerservice-core/src/test/java/org/eclipse/edc/issuerservice/defaults/DefaultServiceExtensionTest.java
  core/issuerservice/issuerservice-core/src/test/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryCredentialDefinitionStoreTest.java
  core/issuerservice/issuerservice-credential-definitions/build.gradle.kts
  core/issuerservice/issuerservice-credential-definitions/src/main/java/org/eclipse/edc/issuerservice/credentialdefinition/CredentialDefinitionServiceExtension.java
  core/issuerservice/issuerservice-credential-definitions/src/main/java/org/eclipse/edc/issuerservice/credentialdefinition/CredentialDefinitionServiceImpl.java
  core/issuerservice/issuerservice-credential-definitions/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/issuerservice/issuerservice-credential-definitions/src/test/java/org/eclipse/edc/issuerservice/credentialdefinition/CredentialDefinitionServiceExtensionTest.java
  core/issuerservice/issuerservice-credential-definitions/src/test/java/org/eclipse/edc/issuerservice/credentialdefinition/CredentialDefinitionServiceImplTest.java
  core/lib/common-lib/src/main/java/org/eclipse/edc/identityhub/store/InMemoryEntityStore.java
  dist/bom/issuerservice-base-bom/build.gradle.kts
  e2e-tests/admin-api-tests/build.gradle.kts
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
  extensions/api/issuer-admin-api/build.gradle.kts
  extensions/api/issuer-admin-api/credential-definition-api/build.gradle.kts
  extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/IssuerCredentialDefinitionAdminApiExtension.java
  extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApi.java
  extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApiController.java
  extensions/api/issuer-admin-api/credential-definition-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/api/issuer-admin-api/credential-definition-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApiControllerTest.java
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  extensions/store/sql/issuerservice-credential-definition-store-sql/build.gradle.kts
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/BaseSqlDialectStatements.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/CredentialDefinitionStoreStatements.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/SqlCredentialDefinitionStore.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/SqlCredentialDefinitionStoreExtension.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/schema/postgres/CredentialDefinitionMapping.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/resources/credential-definition-schema.sql
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/test/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/SqlCredentialDefinitionStoreTest.java
  settings.gradle.kts
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/attestation/AttestationDefinitionStore.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/model/CredentialDefinition.java
  spi/issuerservice/issuerservice-credential-definition-spi/build.gradle.kts
  spi/issuerservice/issuerservice-credential-definition-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentialdefinition/CredentialDefinitionService.java
  spi/issuerservice/issuerservice-credential-definition-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentialdefinition/store/CredentialDefinitionStore.java
  spi/issuerservice/issuerservice-credential-definition-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/credentialdefinition/store/CredentialDefinitionStoreTestBase.java
Labels: enhancement, api

#564 chore: cleanup dependencies
  build.gradle.kts
  core/identity-hub-core/build.gradle.kts
  core/identity-hub-did/build.gradle.kts
  core/identity-hub-keypairs/build.gradle.kts
  core/identity-hub-participants/build.gradle.kts
  core/issuerservice/issuerservice-core/build.gradle.kts
  core/issuerservice/issuerservice-credentials/build.gradle.kts
  core/issuerservice/issuerservice-participants/build.gradle.kts
  core/lib/accesstoken-lib/build.gradle.kts
  core/lib/keypair-lib/build.gradle.kts
  extensions/api/identity-api/participant-context-api/build.gradle.kts
  extensions/api/identity-api/validators/keypair-validators/build.gradle.kts
  extensions/api/identity-api/validators/participant-context-validators/build.gradle.kts
  extensions/api/identity-api/validators/verifiable-credential-validators/build.gradle.kts
  extensions/api/identity-api/verifiable-credentials-api/build.gradle.kts
  extensions/api/identityhub-api-authentication/build.gradle.kts
  extensions/api/identityhub-api-authorization/build.gradle.kts
  extensions/api/issuer-admin-api/attestation-api/build.gradle.kts
  extensions/api/issuer-admin-api/credential-definition-api/build.gradle.kts
  extensions/api/issuer-admin-api/credentials-api/build.gradle.kts
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/build.gradle.kts
  extensions/api/issuer-admin-api/participant-api/build.gradle.kts
  extensions/did/local-did-publisher/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  spi/identity-hub-spi/build.gradle.kts
Labels: refactoring, dependencies

#563 feat: boostrap issuance process state-machine
  core/issuerservice/issuerservice-core/build.gradle.kts
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/DefaultServiceExtension.java
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuanceProcessStore.java
  core/issuerservice/issuerservice-core/src/test/java/org/eclipse/edc/issuerservice/defaults/DefaultServiceExtensionTest.java
  core/issuerservice/issuerservice-core/src/test/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuanceProcessStoreTest.java
  core/issuerservice/issuerservice-issuance/build.gradle.kts
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessServiceImpl.java
  core/issuerservice/issuerservice-issuance/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtensionTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessServiceImplTest.java
  dist/bom/issuerservice-base-bom/build.gradle.kts
  extensions/store/sql/issuance-process-store-sql/build.gradle.kts
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/BaseSqlDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStore.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreExtension.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/sql/issuance-process-store-sql/src/main/resources/issuance-process-schema.sql
  extensions/store/sql/issuance-process-store-sql/src/test/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreTest.java
  gradle/libs.versions.toml
  settings.gradle.kts
  spi/issuance-credentials-spi/build.gradle.kts
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/model/IssuanceProcess.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/model/IssuanceProcessStates.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/process/IssuanceProcessManager.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/process/IssuanceProcessService.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/process/retry/IssuanceProcessRetryStrategy.java
  spi/issuance-credentials-spi/src/main/java/org/eclipse/edc/identityhub/spi/issuance/credentials/process/store/IssuanceProcessStore.java
  spi/issuance-credentials-spi/src/testFixtures/java/org/eclipse/edc/identityhub/spi/issuance/credentials/process/store/IssuanceProcessStoreTestBase.java
Labels: enhancement

#573 chore: improves issuance process query on credentialDefinitions field
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreExtension.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/test/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStoreTest.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/attestationdefinition/schema/postgres/CredentialDefinitionMapping.java
  extensions/store/sql/issuerservice-participant-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/participant/schema/postgres/ParticipantMapping.java
Labels: enhancement

#579 feat: add attestation validation on AttestationDefinitionService
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceServicesExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionValidatorRegistryImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionValidatorRegistryImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  extensions/issuance/issuerservice-issuance-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/IssuanceAttestationsExtension.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/attestation/AttestationDefinitionValidatorRegistry.java
Labels: enhancement

#580 feat: persist VerifiableCredentials
  .github/workflows/verify.yaml
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImpl.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verification/SelfIssuedTokenVerifierImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImplTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verification/SelfIssuedTokenVerifierImplComponentTest.java
  dist/bom/identityhub-base-bom/build.gradle.kts
  e2e-tests/identity-api-tests/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
  e2e-tests/runtimes/identityhub-remote-sts/build.gradle.kts
  protocols/dcp/dcp-identityhub/dcp-identityhub-core/build.gradle.kts
  protocols/dcp/dcp-identityhub/dcp-identityhub-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderCoreExtension.java
  protocols/dcp/dcp-identityhub/dcp-identityhub-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  protocols/dcp/dcp-identityhub/storage-api/build.gradle.kts
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/StorageApiExtension.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/resources/storage-api-version.json
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/IssuerApiExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderTokenVerifierImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderTokenVerifierImplTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtensionTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpHolderTokenVerifier.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpIssuerTokenVerifier.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialMessageTransformer.java
  resources/openapi/issuer-api.version
  resources/openapi/presentation-api.version
  resources/openapi/storage-api.version
  settings.gradle.kts
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/verification/SelfIssuedTokenConstants.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/generator/CredentialWriteRequest.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/generator/CredentialWriter.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialResource.java
Labels: enhancement, dcp, api

#584 refactor: rename IssuanceProcess to avoid confusion
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuanceProcessStore.java
  core/issuerservice/issuerservice-core/src/test/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuerCredentialIssuanceProcessStoreTest.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuerCredentialIssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuerCredentialIssuanceProcessServiceImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/rule/CredentialRuleDefinitionEvaluatorImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtensionTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuerCredentialIssuerCredentialIssuanceProcessServiceImplTest.java
  extensions/issuance/issuerservice-issuance-rules/src/main/java/org/eclipse/edc/issuerservice/issuance/rules/expression/ExpressionCredentialRule.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStore.java
  extensions/store/sql/issuance-process-store-sql/src/test/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuerCredentialIssuanceProcessStoreTest.java
  protocols/dcp/dcp-identityhub/storage-api/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  settings.gradle.kts
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/IssuerCredentialIssuanceContext.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuerCredentialIssuanceProcess.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuerCredentialIssuanceProcessStates.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/process/IssuerCredentialIssuanceProcessManager.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/process/IssuerCredentialIssuanceProcessService.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/process/retry/IssuanceProcessRetryStrategy.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStore.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/rule/CredentialRule.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/rule/CredentialRuleDefinitionEvaluator.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuerCredentialIssuanceProcessStoreTestBase.java
Labels: refactoring

#591 fix: remove unneeded module
  protocols/dcp/dcp-identityhub/storage-api/build.gradle.kts
  settings.gradle.kts
Labels: bug

#594 feat: implement holder-side credential request vertical
  .github/workflows/verify.yaml
  core/identity-hub-core/build.gradle.kts
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImpl.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStore.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImplTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/JwtPresentationGeneratorTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStoreTest.java
  dist/bom/identityhub-bom/build.gradle.kts
  dist/bom/issuerservice-bom/build.gradle.kts
  dist/bom/issuerservice-with-sts-bom/build.gradle.kts
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IssuerServiceRuntimeConfiguration.java
  e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
  e2e-tests/identity-api-tests/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubRuntimeConfiguration.java
  e2e-tests/runtimes/identityhub-remote-sts/build.gradle.kts
  e2e-tests/sts-tests/src/test/java/org/eclipse/edc/identityhub/tests/sts/accountservice/RemoteAccountServiceIntegrationTest.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
  extensions/store/sql/holder-credential-request-store-sql/build.gradle.kts
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/BaseSqlDialectStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/HolderCredentialRequestStoreStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStoreExtension.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/sql/holder-credential-request-store-sql/src/main/resources/holder-credential-request-schema.sql
  extensions/store/sql/holder-credential-request-store-sql/src/test/java/org/eclipse/edc/identityhub/credentialrequest/store/sql/SqlHolderCredentialRequestStoreTest.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/sts/sts-account-service-local/build.gradle.kts
  extensions/sts/sts-account-service-local/src/main/java/org/eclipse/edc/identityhub/sts/LocalStsServiceExtension.java
  extensions/sts/sts-account-service-local/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  gradle/libs.versions.toml
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/StorageApiExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/validation/CredentialRequestMessageValidator.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtensionTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialRequestMessage.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestMessageTransformerTest.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestMessageTransformerTest.java
  settings.gradle.kts
  spi/did-spi/src/main/java/org/eclipse/edc/identityhub/spi/did/model/DidResource.java
  spi/did-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credentialrequest/store/test/DidResourceStoreTestBase.java
  spi/holder-credential-request-spi/build.gradle.kts
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderCredentialRequest.java
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderRequestState.java
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/store/HolderCredentialRequestStore.java
  spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuanceProcess.java
  spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/model/KeyPairResource.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/IdentityResource.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantContext.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestService.java
Labels: enhancement, dcp, api

#597 fix: use transactions in credential request
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImplTest.java
  dist/bom/identityhub-feature-sql-bom/build.gradle.kts
Labels: bug

#602 feat: implement holder credential-request state machine
  core/identity-hub-core/build.gradle.kts
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImpl.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestServiceImplTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGeneratorTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/EdcScopeToCriterionTransformerTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryCredentialStoreTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStoreTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryKeyPairResourceStoreTest.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryParticipantContextStoreTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/VerifiableCredentialApiExtension.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/HolderCredentialRequestStoreStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/resources/holder-credential-request-schema.sql
  spi/did-spi/src/main/java/org/eclipse/edc/identityhub/spi/did/model/DidResource.java
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderCredentialRequest.java
  spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestManager.java
Labels: enhancement, dcp

#603 feat: credentials generation and delivery
  core/issuerservice/issuerservice-issuance/build.gradle.kts
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceServicesExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGenerator.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/mapping/IssuanceClaimsMapperImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtensionTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/mapping/IssuanceClaimsMapperImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  core/lib/issuerservice-common-lib/build.gradle.kts
  core/lib/issuerservice-common-lib/src/main/java/org/eclipse/edc/issuerservice/issuance/common/JsonNavigator.java
  core/lib/issuerservice-common-lib/src/test/java/org/eclipse/edc/issuerservice/issuance/common/JsonNavigatorTest.java
  e2e-tests/admin-api-tests/build.gradle.kts
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IssuerServiceEndToEndTestContext.java
  extensions/issuance/issuerservice-issuance-rules/build.gradle.kts
  extensions/issuance/issuerservice-issuance-rules/src/main/java/org/eclipse/edc/issuerservice/issuance/rules/expression/ExpressionCredentialRule.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/BaseSqlDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStore.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/resources/issuance-process-schema.sql
  gradle/libs.versions.toml
  protocols/dcp/dcp-issuer/dcp-issuer-core/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  settings.gradle.kts
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/delivery/CredentialStorageClient.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGenerationRequest.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGenerator.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGeneratorRegistry.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/mapping/IssuanceClaimsMapper.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuanceProcess.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStoreTestBase.java
Labels: enhancement, dcp

#605 chore: fix after upstream changes on state filtering
  core/common-core/src/main/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStore.java
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryIssuanceProcessStore.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStoreTestBase.java
Labels: bug

#608 feat: introduce holderPid and issuerPid
  core/common-core/src/main/resources/dcp.v1.0.jsonld
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGenerator.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessServiceImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/BaseSqlDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStore.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/resources/issuance-process-schema.sql
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialMessageValidator.java
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialMessageValidatorTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/IssuerApiExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialMessage.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialRequestMessage.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialMessageTransformerTest.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestMessageTransformerTest.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialMessageTransformerTest.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestMessageTransformerTest.java
  protocols/dcp/dcp-validation-lib/build.gradle.kts
  protocols/dcp/dcp-validation-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/validation/CredentialRequestMessageValidator.java
  protocols/dcp/dcp-validation-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/validation/MandatoryId.java
  protocols/dcp/dcp-validation-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/validation/CredentialRequestMessageValidatorTest.java
  protocols/dcp/dcp-validation-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/validation/MandatoryIdTest.java
  settings.gradle.kts
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/delivery/CredentialStorageClient.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuanceProcess.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStoreTestBase.java
Labels: enhancement

#610 refactor: rename requestId and issuanceProcessId
  core/common-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryHolderCredentialRequestStoreTest.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApi.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/CredentialRequestDto.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/HolderCredentialRequestDto.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/BaseSqlDialectStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/HolderCredentialRequestStoreStatements.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/schema/postgres/HolderCredentialRequestMapping.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/resources/holder-credential-request-schema.sql
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderCredentialRequest.java
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderRequestState.java
  spi/holder-credential-request-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credential/request/test/HolderCredentialRequestStoreTestBase.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestManager.java
Labels: refactoring

#612 docs: remove polling requests that are in REQUESTED
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
Labels: bug

#614 feat: add Participant-aware STS
  core/common-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
  core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextServiceImpl.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IdentityHubEndToEndTestContext.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/BaseSqlDialectStatements.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/ParticipantContextStoreStatements.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStore.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/resources/participant-schema.sql
  extensions/sts/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerImpl.java
  extensions/sts/sts-account-service-local/build.gradle.kts
  extensions/sts/sts-account-service-local/src/main/java/org/eclipse/edc/identityhub/sts/AccessTokenDecorator.java
  extensions/sts/sts-account-service-local/src/main/java/org/eclipse/edc/identityhub/sts/EmbeddedSecureTokenService.java
  extensions/sts/sts-account-service-local/src/main/java/org/eclipse/edc/identityhub/sts/LocalStsServiceExtension.java
  extensions/sts/sts-account-service-local/src/main/java/org/eclipse/edc/identityhub/sts/SelfIssuedTokenDecorator.java
  extensions/sts/sts-account-service-local/src/test/java/org/eclipse/edc/identityhub/sts/EmbeddedSecureTokenServiceTest.java
  extensions/sts/sts-account-service-remote/build.gradle.kts
  extensions/sts/sts-account-service-remote/src/main/java/org/eclipse/edc/identityhub/sts/RemoteSecureTokenService.java
  extensions/sts/sts-account-service-remote/src/main/java/org/eclipse/edc/identityhub/sts/RemoteStsServiceExtension.java
  extensions/sts/sts-account-service-remote/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/sts/sts-account-service-remote/src/test/java/org/eclipse/edc/identityhub/sts/RemoteSecureTokenServiceTest.java
  gradle/libs.versions.toml
  protocols/dcp/dcp-issuer/dcp-issuer-core/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/authentication/ParticipantSecureTokenService.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantContext.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantManifest.java
  spi/participant-context-spi/src/testFixtures/java/org/eclipse/edc/identityhub/participantcontext/store/ParticipantContextStoreTestBase.java
Labels: enhancement, dcp

#613 feat: first e2e DCP issuance flow test
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/IssuerServiceEndToEndTestContext.java
  e2e-tests/dcp-issuance-tests/build.gradle.kts
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/fixtures/IssuanceFlowConfig.java
  e2e-tests/fixtures/build.gradle.kts
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractRuntimeConfiguration.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/Endpoint.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/TestFunctions.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubCustomizableEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubRuntimeConfiguration.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
  e2e-tests/identity-api-tests/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  settings.gradle.kts
Labels: enhancement

#619 chore: refactor after upstream changes on postgres tests
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/PostgresSqlService.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndExtension.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
Labels: bug

#622 feat: removes `edc.ih.iam.id` setting
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImplTest.java
  e2e-tests/bom-tests/src/test/java/org/eclipse/edc/test/bom/BomSmokeTests.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/fixtures/IssuanceFlowConfig.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubRuntimeConfiguration.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
  e2e-tests/sts-tests/src/test/java/org/eclipse/edc/identityhub/tests/sts/accountservice/RemoteAccountServiceIntegrationTest.java
  protocols/dcp/dcp-identityhub/dcp-identityhub-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderCoreExtension.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/StorageApiExtension.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtensionTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpIssuerTokenVerifier.java
Labels: enhancement

#620 docs: decision record about STS deployment
  docs/developer/decision-records/2025-02-24-sts-deployment-embedded/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#615 feat: add get-request endpoint for holder requests
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialRequestManagerImpl.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/HolderCredentialRequestDto.java
  extensions/api/identity-api/verifiable-credentials-api/src/test/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiControllerTest.java
  extensions/store/sql/holder-credential-request-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialrequest/schema/SqlHolderCredentialRequestStore.java
  spi/verifiable-credential-spi/build.gradle.kts
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/CredentialRequestManager.java
Labels: enhancement

#624 feat: implements dcp credential request status api
  e2e-tests/admin-api-tests/build.gradle.kts
  e2e-tests/dcp-issuance-tests/build.gradle.kts
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/IssuerApiExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestStatusApiControllerTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialRequestStatus.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestStatusTransformer.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestStatusTransformer.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialRequestStatusTransformerTest.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialRequestStatusTransformerTest.java
Labels: enhancement, dcp

#630 feat: update holder request state upon credential issuance
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImplTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndTestContext.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/VerifiableCredentialsApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/v1/unstable/model/HolderCredentialRequestDto.java
  extensions/sts/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/RandomStringGenerator.java
  extensions/sts/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerExtension.java
  extensions/sts/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerImpl.java
  extensions/sts/sts-account-provisioner/src/main/java/org/eclipse/edc/identityhub/common/provisioner/StsClientSecretGenerator.java
  extensions/sts/sts-account-provisioner/src/test/java/org/eclipse/edc/identityhub/common/provisioner/StsAccountProvisionerImplTest.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
  spi/holder-credential-request-spi/src/main/java/org/eclipse/edc/identityhub/spi/credential/request/model/HolderCredentialRequest.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/generator/CredentialWriter.java
Labels: enhancement, dcp, api

#631 feat: validate incoming CredentialMessage types and formats
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialWriterImplTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  protocols/dcp/dcp-identityhub/storage-api/src/main/java/org/eclipse/edc/identityhub/api/storage/StorageApiController.java
  protocols/dcp/dcp-identityhub/storage-api/src/test/java/org/eclipse/edc/identityhub/api/storage/StorageApiControllerTest.java
Labels: enhancement, dcp, api

#632 fix: add missing SQL modules
  dist/bom/issuerservice-feature-sql-bom/build.gradle.kts
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/participantcontext/SqlParticipantContextStoreExtension.java
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/main/resources/participant-context-schema.sql
  extensions/store/sql/identity-hub-participantcontext-store-sql/src/test/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlParticipantContextStoreTest.java
Labels: bug
