Repository eclipse-edc/IdentityHub, pull requests merged in 2025-04, with the labels that each got.

#695 feat: process CredentialOffers
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialOfferEventPublisher.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialOfferObservableImpl.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialOfferServiceImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialOfferServiceImplTest.java
  dist/bom/identityhub-base-bom/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialOfferApiEndToEndTest.java
  extensions/credentials/credential-offer-handler/build.gradle.kts
  extensions/credentials/credential-offer-handler/src/main/java/org/eclipse/edc/identityhub/credential/offer/handler/CredentialOfferHandler.java
  extensions/credentials/credential-offer-handler/src/main/java/org/eclipse/edc/identityhub/credential/offer/handler/CredentialOfferHandlerExtension.java
  extensions/credentials/credential-offer-handler/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/credentials/credential-offer-handler/src/test/java/org/eclipse/edc/identityhub/credential/offer/handler/CredentialOfferHandlerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
  settings.gradle.kts
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/events/CredentialOfferEvent.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/events/CredentialOfferListener.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/events/CredentialOfferObservable.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/events/CredentialOfferReceived.java
Labels: enhancement, dcp

#696 feat: implement automatic credential renewal
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialStatusCheckServiceImpl.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialStatusCheckServiceImplTest.java
  extensions/common/credential-watchdog/src/main/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdog.java
  extensions/common/credential-watchdog/src/main/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogExtension.java
  extensions/common/credential-watchdog/src/test/java/org/eclipse/edc/identityhub/common/credentialwatchdog/CredentialWatchdogTest.java
Labels: enhancement

#689 fix: prevent 'invalid Uri' error
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGenerator.java
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/generators/LdpPresentationGeneratorTest.java
Labels: bug

#712 fix: Support for custom URL for status list API
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
  extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtensionTest.java
Labels: bug

#711 fix: use mapper embedding date-time in LocalStatusListCredentialPublisherExtension
  extensions/issuance/local-statuslist-publisher/build.gradle.kts
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialController.java
  extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialControllerTest.java
Labels: bug, api

#713 fix: add missing sql dependency to bom and remove not null constraint
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManagerTest.java
  dist/bom/issuerservice-feature-sql-bom/build.gradle.kts
  e2e-tests/dcp-issuance-tests/build.gradle.kts
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalCredentialPublisher.java
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
  extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtensionTest.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/resources/credentials-schema.sql
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java
Labels: bug
