Repository eclipse-edc/IdentityHub, pull requests merged in 2025-03, with the labels that each got.

#636 feat: change dcp issuance base path
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndTestContext.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
Labels: enhancement, api

#646 fix: issuance claims mapper
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/mapping/IssuanceClaimsMapperImplTest.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/mapping/IssuanceClaimsMapper.java
Labels: bug

#647 refactor: extract interface for ParticipantResource
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablepresentation/PresentationCreatorRegistryImpl.java
  core/identity-hub-did/src/main/java/org/eclipse/edc/identityhub/did/DidDocumentServiceImpl.java
  core/identity-hub-keypairs/src/main/java/org/eclipse/edc/identityhub/keypairs/KeyPairServiceImpl.java
  core/identity-hub-participants/src/main/java/org/eclipse/edc/identityhub/participantcontext/ParticipantContextEventCoordinator.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessServiceImplTest.java
  core/lib/keypair-lib/src/main/java/org/eclipse/edc/identityhub/publickey/KeyPairResourcePublicKeyResolver.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/IssuanceProcessApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndTestContext.java
  extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/KeyPairResourceManagementApiExtension.java
  extensions/api/identity-api/keypair-api/src/main/java/org/eclipse/edc/identityhub/api/keypair/v1/unstable/KeyPairResourceApiController.java
  extensions/api/identity-api/verifiable-credentials-api/src/main/java/org/eclipse/edc/identityhub/api/verifiablecredentials/VerifiableCredentialApiExtension.java
  extensions/api/identityhub-api-authorization/src/test/java/org/eclipse/edc/identityhub/api/authorization/AuthorizationServiceImplTest.java
  extensions/api/issuer-admin-api/issuance-process-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/issuance/IssuanceProcessAdminApiExtension.java
  extensions/api/issuer-admin-api/issuance-process-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/issuance/v1/unstable/IssuanceProcessAdminApi.java
  extensions/api/issuer-admin-api/issuance-process-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/issuance/v1/unstable/IssuanceProcessAdminApiController.java
  extensions/api/issuer-admin-api/issuance-process-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/issuance/v1/unstable/model/IssuanceProcessDto.java
  extensions/api/issuer-admin-api/issuance-process-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/issuance/v1/unstable/IssuanceProcessAdminApiControllerTest.java
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/BaseSqlDialectStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/IssuanceProcessStoreStatements.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/SqlIssuanceProcessStore.java
  extensions/store/sql/issuance-process-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/issuanceprocess/schema/postgres/IssuanceProcessMapping.java
  extensions/store/sql/issuance-process-store-sql/src/main/resources/issuance-process-schema.sql
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApi.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequeststatus/CredentialRequestStatusApiController.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/main/resources/issuer-api-version.json
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestStatusApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpCredentialStorageClient.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/spi/DcpIssuerService.java
  spi/did-spi/src/main/java/org/eclipse/edc/identityhub/spi/did/model/DidResource.java
  spi/did-spi/src/testFixtures/java/org/eclipse/edc/identityhub/credentialrequest/store/test/DidResourceStoreTestBase.java
  spi/identity-hub-spi/src/main/java/org/eclipse/edc/identityhub/spi/authorization/AuthorizationService.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGeneratorRegistry.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuanceProcess.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/IssuanceProcessResource.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/process/store/IssuanceProcessStoreTestBase.java
  spi/keypair-spi/src/main/java/org/eclipse/edc/identityhub/spi/keypair/model/KeyPairResource.java
  spi/keypair-spi/src/testFixtures/java/org/eclipse/edc/identityhub/keypair/store/KeyPairResourceStoreTestBase.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/AbstractParticipantResource.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/IdentityResource.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantContext.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/model/ParticipantResource.java
  spi/participant-context-spi/src/main/java/org/eclipse/edc/identityhub/spi/participantcontext/store/ParticipantContextStore.java
  spi/participant-context-spi/src/testFixtures/java/org/eclipse/edc/identityhub/participantcontext/store/ParticipantContextStoreTestBase.java
  spi/verifiable-credential-spi/src/testFixtures/java/org/eclipse/edc/identityhub/verifiablecredentials/store/CredentialStoreTestBase.java
Labels: refactoring

#649 feat: implement database attestations
  dist/bom/issuerservice-base-bom/build.gradle.kts
  dist/bom/issuerservice-feature-sql-bom/build.gradle.kts
  extensions/issuance/issuerservice-database-attestations/build.gradle.kts
  extensions/issuance/issuerservice-database-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/DatabaseAttestationExtension.java
  extensions/issuance/issuerservice-database-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/database/DatabaseAttestationSource.java
  extensions/issuance/issuerservice-database-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/database/DatabaseAttestationSourceFactory.java
  extensions/issuance/issuerservice-database-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/database/DatabaseAttestationSourceValidator.java
  extensions/issuance/issuerservice-database-attestations/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/issuance/issuerservice-database-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/database/DatabaseAttestationSourceFactoryTest.java
  extensions/issuance/issuerservice-database-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/database/DatabaseAttestationSourceTest.java
  extensions/issuance/issuerservice-database-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/database/DatabaseAttestationSourceValidatorTest.java
  extensions/issuance/issuerservice-database-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/database/TestAttestationContext.java
  extensions/issuance/issuerservice-database-attestations/src/test/resources/test-attestation-table.sql
  extensions/issuance/issuerservice-presentation-attestations/build.gradle.kts
  extensions/issuance/issuerservice-presentation-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/PresentationAttestationExtension.java
  extensions/issuance/issuerservice-presentation-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestationSource.java
  extensions/issuance/issuerservice-presentation-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestationSourceFactory.java
  extensions/issuance/issuerservice-presentation-attestations/src/main/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestatonSourceValidator.java
  extensions/issuance/issuerservice-presentation-attestations/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/issuance/issuerservice-presentation-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestationSourceFactoryTest.java
  extensions/issuance/issuerservice-presentation-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestationSourceTest.java
  extensions/issuance/issuerservice-presentation-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/PresentationAttestationSourceValidatorTest.java
  extensions/issuance/issuerservice-presentation-attestations/src/test/java/org/eclipse/edc/issuerservice/issuance/attestations/presentation/TestAttestationContext.java
  settings.gradle.kts
Labels: enhancement, dcp

#653 refactor: removes attestation linkage to holders
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceServicesExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/attestation/AttestationDefinitionServiceImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/HolderApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
  extensions/api/issuer-admin-api/attestation-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApi.java
  extensions/api/issuer-admin-api/attestation-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApiController.java
  extensions/api/issuer-admin-api/attestation-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerAttestationAdminApiControllerTest.java
  extensions/api/issuer-admin-api/holder-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/holder/v1/unstable/IssuerHolderAdminApiControllerTest.java
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/BaseSqlDialectStatements.java
  extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/HolderStoreStatements.java
  extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/SqlHolderStore.java
  extensions/store/sql/issuerservice-holder-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/holder/schema/postgres/HolderMapping.java
  extensions/store/sql/issuerservice-holder-store-sql/src/main/resources/holder-schema.sql
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-api/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/api/v1alpha/credentialrequest/CredentialRequestStatusApiControllerTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpHolderTokenVerifierImplTest.java
  spi/issuerservice/issuerservice-holder-spi/src/main/java/org/eclipse/edc/issuerservice/spi/holder/model/Holder.java
  spi/issuerservice/issuerservice-holder-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/holder/store/HolderStoreTestBase.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/attestation/AttestationDefinitionService.java
Labels: refactoring

#654 feat: add signing capability to credential generator
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGenerator.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGenerator.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/generator/CredentialGeneratorRegistry.java
Labels: enhancement

#645 feat: switch JTI validation to black-listing
  extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/EmbeddedStsServiceExtension.java
  extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/service/EmbeddedSecureTokenService.java
  extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsAccountTokenIssuanceIntegrationTest.java
  extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/service/EmbeddedSecureTokenServiceTest.java
Labels: enhancement

#655 feat: create status list entry on new credential
  core/issuerservice/issuerservice-credentials/build.gradle.kts
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialStatusServiceImpl.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/StatusListInfoFactoryRegistryImpl.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringConstants.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListCredentialEntry.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/CredentialStatusServiceImplTest.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManagerTest.java
  core/issuerservice/issuerservice-issuance/build.gradle.kts
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/IssuanceCoreExtension.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImpl.java
  core/issuerservice/issuerservice-issuance/src/main/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImpl.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/IssuerCredentialsAdminApiExtension.java
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiController.java
  extensions/api/issuer-admin-api/credentials-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiControllerTest.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/BaseSqlDialectStatements.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/CredentialStoreStatements.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/SqlCredentialStore.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentials/schema/postgres/VerifiableCredentialResourceMapping.java
  extensions/store/sql/identity-hub-credentials-store-sql/src/main/resources/credentials-schema.sql
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/CredentialStatusService.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialEntry.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListInfoFactoryRegistry.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListManager.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/VerifiableCredentialResource.java
  spi/verifiable-credential-spi/src/testFixtures/java/org/eclipse/edc/identityhub/verifiablecredentials/store/CredentialStoreTestBase.java
Labels: enhancement

#660 feat: implement Admin API to trigger CredentialOffers
  core/issuerservice/issuerservice-credentials/build.gradle.kts
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImpl.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImplTest.java
  e2e-tests/admin-api-tests/build.gradle.kts
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceCustomizableEndToEndExtension.java
  extensions/api/identity-api/api-configuration/src/main/resources/identity-api-version.json
  extensions/api/issuer-admin-api/credentials-api/build.gradle.kts
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/IssuerCredentialsAdminApiExtension.java
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApi.java
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiController.java
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/model/CredentialOfferDto.java
  extensions/api/issuer-admin-api/credentials-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentials/v1/unstable/IssuerCredentialsAdminApiControllerTest.java
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/CredentialDescriptor.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/IssuerCredentialOfferService.java
Labels: api

#665 chore: refactor E2E tests
  core/identity-hub-core/src/test/java/org/eclipse/edc/identityhub/core/services/verification/SelfIssuedTokenVerifierImplComponentTest.java
  e2e-tests/admin-api-tests/build.gradle.kts
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/AttestationApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/HolderApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/IssuanceProcessApiEndToEndTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/TestData.java
  e2e-tests/dcp-issuance-tests/build.gradle.kts
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/TestData.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestStatusApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractRuntimeConfiguration.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubCustomizableEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubEndToEndTestContext.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubRuntimeConfiguration.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceCustomizableEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceEndToEndExtension.java
  e2e-tests/fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerServiceRuntimeConfiguration.java
  e2e-tests/identity-api-tests/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/DidManagementApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/KeyPairResourceApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/ParticipantContextApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/PresentationApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/StorageApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/VerifiableCredentialApiEndToEndTest.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/TestData.java
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/fixtures/TestFunctions.java
  e2e-tests/identityhub-test-fixtures/build.gradle.kts
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractIdentityHubExtension.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/AbstractIdentityHubRuntime.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/ComponentExtension.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/Endpoint.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/LazySupplier.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/Named.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/common/TestFunctions.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubApiClient.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubExtension.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/credentialservice/IdentityHubRuntime.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerExtension.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerRuntime.java
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: refactoring

#664 feat: add StatusList credential endpoint
  core/issuerservice/issuerservice-core/build.gradle.kts
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManager.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/statuslist/bitstring/BitstringStatusListManagerTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  e2e-tests/identityhub-test-fixtures/src/testFixtures/java/org/eclipse/edc/identityhub/tests/fixtures/issuerservice/IssuerExtension.java
  extensions/issuance/local-statuslist-publisher/build.gradle.kts
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalCredentialPublisher.java
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/LocalStatusListCredentialPublisherExtension.java
  extensions/issuance/local-statuslist-publisher/src/main/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialController.java
  extensions/issuance/local-statuslist-publisher/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/issuance/local-statuslist-publisher/src/test/java/org/eclipse/edc/issuerservice/publisher/api/StatusListCredentialControllerTest.java
  settings.gradle.kts
  spi/did-spi/src/main/java/org/eclipse/edc/identityhub/spi/did/DidDocumentPublisher.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListCredentialPublisher.java
  spi/issuerservice/issuerservice-credential-spi/src/main/java/org/eclipse/edc/issuerservice/spi/credentials/statuslist/StatusListManager.java
Labels: enhancement, api

#666 fix: use `id` insted of `clientId` when generating the token
  extensions/sts/sts-core/src/main/java/org/eclipse/edc/iam/identitytrust/sts/service/StsClientTokenGeneratorServiceImpl.java
  extensions/sts/sts-core/src/test/java/org/eclipse/edc/iam/identitytrust/sts/defaults/StsAccountTokenIssuanceIntegrationTest.java
Labels: bug

#678 refactor: removes dataModel in CredentialDefinition
  core/issuerservice/issuerservice-core/build.gradle.kts
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/CredentialDefinitionLookup.java
  core/issuerservice/issuerservice-core/src/main/java/org/eclipse/edc/issuerservice/defaults/store/InMemoryCredentialDefinitionStore.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/CredentialGeneratorRegistryImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/generator/JwtCredentialGeneratorTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/issuance/credentialdefinition/CredentialDefinitionServiceImplTest.java
  core/issuerservice/issuerservice-issuance/src/test/java/org/eclipse/edc/issuerservice/issuance/process/IssuanceProcessManagerImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialDefinitionApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/api/DcpCredentialRequestApiEndToEndTest.java
  e2e-tests/dcp-issuance-tests/src/test/java/org/eclipse/edc/identityhub/tests/dcp/flow/DcpIssuanceFlowEndToEndTest.java
  extensions/api/issuer-admin-api/credential-definition-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/model/CredentialDefinitionDto.java
  extensions/api/issuer-admin-api/credential-definition-api/src/test/java/org/eclipse/edc/issuerservice/api/admin/credentialdefinition/v1/unstable/IssuerCredentialDefinitionAdminApiControllerTest.java
  extensions/api/issuer-admin-api/issuer-admin-api-configuration/src/main/resources/issuer-admin-api-version.json
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/BaseSqlDialectStatements.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/CredentialDefinitionStoreStatements.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/SqlCredentialDefinitionStore.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/java/org/eclipse/edc/issuerservice/store/sql/credentialdefinition/schema/postgres/CredentialDefinitionMapping.java
  extensions/store/sql/issuerservice-credential-definition-store-sql/src/main/resources/credential-definition-schema.sql
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  spi/issuerservice/issuerservice-issuance-spi/src/main/java/org/eclipse/edc/issuerservice/spi/issuance/model/CredentialDefinition.java
  spi/issuerservice/issuerservice-issuance-spi/src/testFixtures/java/org/eclipse/edc/issuerservice/spi/issuance/credentialdefinition/store/CredentialDefinitionStoreTestBase.java
Labels: enhancement

#675 feat: Issuer sends CredentialOffers
  core/issuerservice/issuerservice-credentials/build.gradle.kts
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/CredentialServiceExtension.java
  core/issuerservice/issuerservice-credentials/src/main/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImpl.java
  core/issuerservice/issuerservice-credentials/src/test/java/org/eclipse/edc/issuerservice/credentials/offers/IssuerCredentialOfferServiceImplTest.java
  e2e-tests/admin-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialApiEndToEndTest.java
  extensions/api/issuer-admin-api/credentials-api/build.gradle.kts
  extensions/api/issuer-admin-api/credentials-api/src/main/java/org/eclipse/edc/issuerservice/api/admin/credentials/IssuerCredentialsAdminApiExtension.java
Labels: enhancement, dcp, api

#679 feat: introduce DCP profile
  dist/bom/identityhub-base-bom/build.gradle.kts
  dist/bom/issuerservice-base-bom/build.gradle.kts
  protocols/dcp/dcp-core/build.gradle.kts
  protocols/dcp/dcp-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/DcpCoreExtension.java
  protocols/dcp/dcp-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/DcpProfileRegistryImpl.java
  protocols/dcp/dcp-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  protocols/dcp/dcp-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/DcpCoreExtensionTest.java
  protocols/dcp/dcp-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/DcpProfileRegistryImplTest.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/build.gradle.kts
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerCoreExtension.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImpl.java
  protocols/dcp/dcp-issuer/dcp-issuer-core/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/issuer/DcpIssuerServiceImplTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpProfileRegistry.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/DcpProfile.java
  settings.gradle.kts
Labels: enhancement

#685 feat: holder-side Credential Offer API
  protocols/dcp/dcp-identityhub/credential-offer-api/build.gradle.kts
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/CredentialOfferApiExtension.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/ApiSchema.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApi.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiController.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialObjectValidator.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidator.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/JsonValidator.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiControllerTest.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidatorTest.java
  protocols/dcp/dcp-identityhub/credentials-api-configuration/src/main/resources/credentials-api-version.json
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/DcpConstants.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialOfferMessage.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialOfferMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialOfferMessageTransformer.java
  settings.gradle.kts
Labels: enhancement, dcp, api

#687 feat: add persistence for CredentialOffers (holder-side)
  core/common-core/src/main/java/org/eclipse/edc/identityhub/DefaultServicesExtension.java
  core/common-core/src/main/java/org/eclipse/edc/identityhub/defaults/store/InMemoryCredentialOfferStore.java
  core/common-core/src/test/java/org/eclipse/edc/identityhub/defaults/store/InMemoryCredentialOfferStoreTest.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/CoreServicesExtension.java
  core/identity-hub-core/src/main/java/org/eclipse/edc/identityhub/core/services/verifiablecredential/CredentialOfferServiceImpl.java
  dist/bom/identityhub-base-bom/build.gradle.kts
  dist/bom/identityhub-feature-sql-bom/build.gradle.kts
  e2e-tests/identity-api-tests/src/test/java/org/eclipse/edc/identityhub/tests/CredentialOfferApiEndToEndTest.java
  extensions/store/sql/holder-credential-offer-store-sql/build.gradle.kts
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/BaseSqlDialectStatements.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/CredentialOfferStoreStatements.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/SqlCredentialOfferStore.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/SqlCredentialOfferStoreExtension.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/schema/postgres/CredentialOfferMapping.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/java/org/eclipse/edc/identityhub/store/sql/credentialoffer/schema/schema/postgres/PostgresDialectStatements.java
  extensions/store/sql/holder-credential-offer-store-sql/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
  extensions/store/sql/holder-credential-offer-store-sql/src/main/resources/credential-offer-schema.sql
  extensions/store/sql/holder-credential-offer-store-sql/src/test/java/org/eclipse/edc/identityhub/credentialoffer/store/sql/SqlCredentialOfferStoreTest.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/CredentialOfferApiExtension.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiController.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialObjectValidator.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/main/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidator.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/credentialoffer/CredentialOfferApiControllerTest.java
  protocols/dcp/dcp-identityhub/credential-offer-api/src/test/java/org/eclipse/edc/identityhub/api/validation/CredentialOfferMessageValidatorTest.java
  protocols/dcp/dcp-spi/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/spi/model/CredentialOfferMessage.java
  protocols/dcp/dcp-transform-lib/src/main/java/org/eclipse/edc/identityhub/protocols/dcp/transform/to/JsonObjectToCredentialOfferMessageTransformer.java
  protocols/dcp/dcp-transform-lib/src/test/java/org/eclipse/edc/identityhub/protocols/dcp/transform/from/JsonObjectFromCredentialOfferMessageTransformerTest.java
  settings.gradle.kts
  spi/verifiable-credential-spi/build.gradle.kts
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/CredentialObject.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/CredentialOffer.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/model/CredentialOfferStatus.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/offer/CredentialOfferService.java
  spi/verifiable-credential-spi/src/main/java/org/eclipse/edc/identityhub/spi/verifiablecredentials/store/CredentialOfferStore.java
  spi/verifiable-credential-spi/src/testFixtures/java/org/eclipse/edc/identityhub/verifiablecredentials/store/CredentialOfferStoreTestBase.java
Labels: enhancement, dcp, api
